### ISSUE TITLE
Preview does not display features in example

### ISSUE THREAD

**Issue by kneemer** [koopjs/koop-gist#7]
Using the provided example and navigating to http://localhost:1337/gist/6178185/preview, a map displays with no features.  The console displays the error:

`Uncaught TypeError: a.replace is not a function`

It looks like the Esri Leaflet version being used (RC 3) did not minify well on the cleanUrl method.

The issue also occurs on http://koop.dc.esri.com/gist/6178185/preview

**Comment by kneemer** [comment]
I see that @jgravois already addressed this in https://github.com/koopjs/koop-github/pull/22 so this should bring parity between the two previews.

**Comment by ngoldman** [comment]
:+1:
